Add conversion of state label columns to str if necessary
Becksteinlab/multibind pull request #22
Opened 2023-12-13 21:57 UTC by l-repa

pd.read_csv by default sets columns to int or float if they are purely numeric, which causes the string matching done later to fail and return an empty dataframe (which then throws an error when attempting to access its elements)

2023-12-15 16:55 UTC, ianmkenney requested changes
pandas uses object arrays for strings because of their variable length and is really an issue for performance. I'm not sure how long the `object` solution will work. It might break if they change string representations. For instance see this experimental feature in pandas.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.StringDtype.html#pandas.StringDtype

I would instead suggest we tell `read_csv` which datatypes are needed for each column. You can specify `str` for the state columns and it will default to the `object` datatype. I assume that if they change how they represent strings, this will still work.

2023-12-15 23:34 UTC, l-repa commented
Good idea, changed to use dtype kwarg in pd.read_csv instead to specify the state columns should be str.

2023-12-18 17:02 UTC, ianmkenney commented on multibind/nonequilibrium.py
> +
```suggestion

```

2023-12-18 17:04 UTC, ianmkenney approved these changes
Thanks @l-repa

2023-12-18 17:05 UTC, merged